// SPDX-License-Identifier: LGPL-3.0-only
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {LibZip} from "solady/utils/LibZip.sol";

/// @notice Cross-compatibility guard: a FastLZ stream produced by the toolkit's off-chain
///         encoder (the SDK's pure-JS `flzCompress`) must inflate correctly under Solady's
///         on-chain `LibZip.flzDecompress` — the decoder the `AbxChunkStore` reader uses.
///         The fixture was generated by that JS encoder; if the encoder's byte format ever
///         drifts from the decoder, this test fails.
contract FastLzCompatTest is Test {
    function test_JsEncodedStream_DecodesOnChain() public pure {
        // flzCompress(bytes("on-chain on-chain on-chain content content content for the cross check check check"))
        bytes memory compressed =
            hex"086f6e2d636861696e20e0090806636f6e74656e74e0080712666f72207468652063726f737320636865636be00305";
        bytes memory expected = bytes(
            "on-chain on-chain on-chain content content content for the cross check check check"
        );
        assertEq(LibZip.flzDecompress(compressed), expected);
    }
}
