/**
 * sync-abis — the contracts → SDK pipeline.
 *
 * Reads the Foundry build artifacts from `contracts/out/` and emits a single
 * generated TypeScript module the SDK imports. Re-run whenever the contracts
 * change (`forge build` first). This keeps the SDK's notion of the ABI and
 * creation bytecode exactly in lock-step with Layer 1 — never hand-edited.
 *
 *   pnpm --filter @artblocks/abx-sdk sync-abis      (or: pnpm sync-abis at the root)
 */
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, resolve} from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const contractsOut = resolve(here, '../../../contracts/out');
const outFile = resolve(here, '../src/abi/generated.ts');

// (artifactPath, export base name) — the contracts the SDK needs to speak to.
const ARTIFACTS: ReadonlyArray<[string, string]> = [
  ['OneOfOneImageFactory.sol/OneOfOneImageFactory.json', 'oneOfOneImageFactory'],
  ['OneOfOneImage.sol/OneOfOneImage.json', 'oneOfOneImage'],
  ['SeriesImageFactory.sol/SeriesImageFactory.json', 'seriesImageFactory'],
  ['SeriesImage.sol/SeriesImage.json', 'seriesImage'],
  ['SeriesCodeFactory.sol/SeriesCodeFactory.json', 'seriesCodeFactory'],
  ['SeriesCode.sol/SeriesCode.json', 'seriesCode'],
  ['OneOfOneEditionFactory.sol/OneOfOneEditionFactory.json', 'oneOfOneEditionFactory'],
  ['OneOfOneEdition.sol/OneOfOneEdition.json', 'oneOfOneEdition'],
  ['EditionImageFactory.sol/EditionImageFactory.json', 'editionImageFactory'],
  ['EditionImage.sol/EditionImage.json', 'editionImage'],
  ['EditionCodeFactory.sol/EditionCodeFactory.json', 'editionCodeFactory'],
  ['EditionCode.sol/EditionCode.json', 'editionCode'],
  ['AbxEditionLib.sol/AbxEditionLib.json', 'abxEditionLib'],
  ['AbxMetadataLib.sol/AbxMetadataLib.json', 'abxMetadataLib'],
  ['AbxFixedPriceMinter1155.sol/AbxFixedPriceMinter1155.json', 'abxFixedPriceMinter1155'],
  ['AbxSeedSource.sol/AbxSeedSource.json', 'abxSeedSource'],
  ['AbxParamsLib.sol/AbxParamsLib.json', 'abxParamsLib'],
  ['AbxCodeLib.sol/AbxCodeLib.json', 'abxCodeLib'],
  ['AbxFixedPriceMinter.sol/AbxFixedPriceMinter.json', 'abxFixedPriceMinter'],
  ['AbxMetadataRenderer.sol/AbxMetadataRenderer.json', 'abxMetadataRenderer'],
  ['AbxChunkStore.sol/AbxChunkStore.json', 'abxChunkStore'],
];

function load(artifactRelPath: string) {
  const json = JSON.parse(readFileSync(resolve(contractsOut, artifactRelPath), 'utf8'));
  return {abi: json.abi, bytecode: json.bytecode?.object ?? '0x'};
}

let body = `// AUTO-GENERATED by packages/sdk/scripts/sync-abis.ts — do not edit by hand.
// Source: contracts/out (Foundry artifacts). Re-run \`pnpm sync-abis\` after \`forge build\`.
/* eslint-disable */
`;

for (const [artifactPath, base] of ARTIFACTS) {
  const {abi, bytecode} = load(artifactPath);
  body += `\nexport const ${base}Abi = ${JSON.stringify(abi)} as const;\n`;
  body += `export const ${base}Bytecode = ${JSON.stringify(bytecode)} as \`0x\${string}\`;\n`;
}

writeFileSync(outFile, body);
console.log(`Wrote ${outFile} (${ARTIFACTS.length} artifacts).`);
