/**
 * Hosted-resolver provisioning — scaffolds a **self-contained** deploy artifact for the read-only
 * ABX token API to a provider the operator owns, under a custom domain they control.
 *
 * Every provider emits its own `Dockerfile` and `.dockerignore` alongside its config, producing a
 * complete artifact that does not depend on paths in this repository.
 *
 * TWO WAYS the image obtains the ABX code:
 *   - **Production (default):** an npm-based image — `npm i -g @artblocks/abx-cli` → `abx serve`. Tiny, no
 *     build step, self-contained.
 *   - **Dev (`fromSource`):** build from the workspace source the CLI vendors INTO the artifact
 *     dir, so it builds pre-publish. Same `abx serve` entrypoint; converges to the npm image after
 *     publish. This is a permanent dev capability — we sandbox-e2e locally without publishing.
 *
 * This is the DEFAULT off-chain path: the resolver builds metadata dynamically from chain + IPFS,
 * so changing name/description/etc. never touches the on-chain pointer — only a frozen `ipfs://`
 * override does. The provisioned host is **read-only**: it serves the token API (`abx serve`) and
 * holds NO signing key — every write is signed locally by the CLI. So the worst a compromised host
 * can do is serve wrong bytes, which the on-chain keccak commitment lets anyone detect.
 *
 * Pure module: it returns the artifact files + the exact next-step commands. The CLI writes the
 * files (and, for `fromSource`, vendors the workspace source next to them) and prints the steps;
 * running `fly deploy` / a Render blueprint / the VPS setup needs the operator's own cloud account,
 * so the human owns that final step.
 */

export type ResolverProvider = 'fly' | 'render' | 'vps';

export interface ResolverArtifact {
  /** Files to write, relative to the chosen output dir. */
  files: Array<{path: string; content: string}>;
  /** Ordered, copy-pasteable next steps the operator runs (from the artifact dir). */
  steps: string[];
  /** The single DNS record that points the custom domain at the host (if a domain was given). */
  dns?: string;
  /** One-line hardening summary for this provider. */
  hardening: string;
  /** The public URL baked into ABX_PUBLIC_BASE_URL — the resolver builds its own metadata URLs from this. */
  baseUrl: string;
}

export interface ResolverOptions {
  provider: ResolverProvider;
  /** App/service name (provider dashboards key off this). */
  app: string;
  /** Custom domain to bake on-chain — re-point DNS, not an on-chain tx, if you ever move hosts. */
  domain?: string;
  /** Chain key the resolver serves (default base-sepolia). */
  chain?: string;
  /** DEV: build the image from vendored workspace source instead of the npm package. */
  fromSource?: boolean;
  /** DEV (fromSource): workspace package dirs to COPY, e.g. `packages/sdk` — supplied by the CLI. */
  sourcePackages?: string[];
  /** DEV (fromSource): pnpm version to pin in the image (from the repo's `packageManager`). */
  pnpmVersion?: string;
}

const PORT = 8787;

/**
 * The public URL the resolver serves its own metadata (image/animation/tokenURI) URLs from — baked
 * into ABX_PUBLIC_BASE_URL. With a custom --domain we bake THAT (portable: moving hosts is a DNS
 * change, not an on-chain re-point). Without one we bake the provider's REAL platform hostname so the
 * resolver works out of the box — never a dead `.example` placeholder; add a custom domain later.
 * (vps derives its own base from --domain and never calls this.)
 */
const baseUrlFor = (o: ResolverOptions): string => {
  if (o.domain) return `https://${o.domain}`;
  if (o.provider === 'fly') return `https://${o.app}.fly.dev`;
  if (o.provider === 'render') return `https://${o.app}.onrender.com`;
  throw new Error(`provider '${o.provider}' has no default hostname — pass --domain`);
};

/** Production image: the published CLI from npm. Tiny, self-contained, no build step. */
function npmDockerfile(o: ResolverOptions): string {
  return `# Generated by \`abx deploy-resolver\`. Self-contained, read-only ABX resolver (token API).
# PRODUCTION image — installs the published CLI from npm. No repo, no build step, nothing to copy.
FROM node:24-slim
# --no-optional drops @artblocks/abx-effects + Playwright: the resolver serves read-only and never
# renders, so it stays small + browserless. (Rendering is the effects runner's job — see deploy-effects.)
RUN npm install -g --no-optional @artblocks/abx-cli@latest
# The disposable SQLite projection lives here (replay rebuilds it); a volume persists it.
# ABX_HOSTED=1 marks a hosted image so the resolver refuses a localhost/placeholder base URL.
ENV ABX_DATA_DIR=/data ABX_PORT=${PORT} ABX_CHAIN=${o.chain ?? 'base-sepolia'} ABX_HOSTED=1
VOLUME /data
EXPOSE ${PORT}
CMD ["abx", "serve"]
`;
}

/** DEV image: build from the workspace source the CLI vendored next to this Dockerfile — no npm
 *  publish needed. Production omits this and gets the tiny npm image; same `abx serve` entrypoint. */
function sourceDockerfile(o: ResolverOptions): string {
  const copyManifests = (o.sourcePackages ?? []).map((p) => `COPY ${p}/package.json ${p}/`).join('\n');
  return `# Generated by \`abx deploy-resolver --from-source\` (DEV). Builds the resolver from the
# workspace source the CLI vendored into THIS directory — no npm publish required. Production omits
# --from-source and gets a tiny npm-based image instead. Same entrypoint (\`abx serve\`) either way.
FROM node:24-slim
RUN corepack enable && corepack prepare pnpm@${o.pnpmVersion ?? '10.28.0'} --activate
WORKDIR /app
# Deps first (this layer caches across source edits). Every workspace package.json MUST be copied,
# or pnpm optimistically symlinks a package whose node_modules is never created — a runtime crash.
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
${copyManifests}
RUN pnpm install --frozen-lockfile
# Source (the SDK ships committed ABIs, so neither contracts/ nor forge is needed).
COPY packages/ packages/
# ABX_HOSTED=1 marks a hosted image so the resolver refuses a localhost/placeholder base URL.
ENV ABX_DATA_DIR=/data ABX_PORT=${PORT} ABX_CHAIN=${o.chain ?? 'base-sepolia'} ABX_HOSTED=1
VOLUME /data
EXPOSE ${PORT}
CMD ["pnpm", "abx", "serve"]
`;
}

const dockerfileFor = (o: ResolverOptions): string => (o.fromSource ? sourceDockerfile(o) : npmDockerfile(o));

const DOCKERIGNORE = `# Generated by \`abx deploy-resolver\`. Keeps the build context small + reproducible.
**/node_modules
**/dist
**/.turbo
**/*.log
.git
.env
.abx-self-host
`;

// Load the two local secrets from your .env (at the project root, two levels up from deploy/<provider>/)
// so the literal values never land in your shell history — the fix for accidentally inlining an RPC URL.
const loadEnv = `set -a; . ../../.env 2>/dev/null; set +a   # load your local secrets (sourced, never printed)`;

/** Fly.io — runs the emitted Dockerfile, persistent volume for the SQLite projection, force-HTTPS. */
function fly(o: ResolverOptions): ResolverArtifact {
  const toml = `# Generated by \`abx deploy-resolver --provider fly\`. Read-only ABX resolver (token API).
app = "${o.app}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"   # emitted right here — self-contained, no repo files needed

[env]
  ABX_CHAIN = "${o.chain ?? 'base-sepolia'}"
  ABX_PORT = "${PORT}"
  # The URL this resolver serves its own metadata (image/animation) URLs from. With --domain we bake
  # your domain (portable — moving hosts is a DNS change, not an on-chain re-point); without one we
  # bake the real *.fly.dev hostname so it works out of the box. Add a custom domain later.
  ABX_PUBLIC_BASE_URL = "${baseUrlFor(o)}"

[http_service]
  internal_port = ${PORT}
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

# The SQLite projection is disposable (replay rebuilds it) but a volume avoids a cold reindex.
[mounts]
  source = "abx_data"
  destination = "/data"

# The image runs the CLI through tsx (transpiles the workspace at boot); the 256MB shared default
# thrashes and never binds. 512MB serves comfortably.
[[vm]]
  memory = "512mb"
`;
  return {
    baseUrl: baseUrlFor(o),
    files: [
      {path: 'Dockerfile', content: dockerfileFor(o)},
      {path: '.dockerignore', content: DOCKERIGNORE},
      {path: 'fly.toml', content: toml},
    ],
    steps: [
      `fly version && fly auth whoami   # confirm fly is installed + you're logged in ('flyctl' and 'fly' are the same binary)`,
      `fly launch --no-deploy --copy-config --name ${o.app}   # uses the Dockerfile + fly.toml in THIS dir`,
      `fly volumes create abx_data --size 1 --region iad   # BEFORE first deploy — the SQLite projection lives here; skip it and a redeploy/restart loses the index (and any published render locators)`,
      loadEnv,
      `fly secrets set ABX_RPC_URLS="$ABX_RPC_URLS"   # read-only RPC for this chain; NO signing key on the host`,
      // The admin token authorizes remote `abx add`/index (NOT signing). LHS is the resolver's OWN
      // var name (server-side, unchanged); RHS pulls the value from your local ABX_REMOTE_SELF_TOKEN
      // (the named-remote grammar's "self" entry — `abx deploy-resolver` generated + saved it).
      `fly secrets set ABX_RESOLVER_ADMIN_TOKEN="$ABX_REMOTE_SELF_TOKEN"   # index-control only, never signing`,
      `fly deploy`,
      o.domain ? `fly certs add ${o.domain}` : `# (add a custom domain: fly certs add meta.yourproject.xyz)`,
    ],
    dns: o.domain ? `${o.domain}  CNAME  ${o.app}.fly.dev   (or the A/AAAA records 'fly certs show' prints)` : undefined,
    hardening: 'force_https on; no signing key (read-only serve); RPC url is the only secret, sourced from .env.',
  };
}

/** Render — Docker web service blueprint, free tier, persistent disk, health check. */
function render(o: ResolverOptions): ResolverArtifact {
  const yaml = `# Generated by \`abx deploy-resolver --provider render\`. Read-only ABX resolver (token API).
services:
  - type: web
    name: ${o.app}
    runtime: docker
    rootDir: deploy/render      # build context = this artifact dir (self-contained; holds the Dockerfile)
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    disk:
      name: abx-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: ABX_CHAIN
        value: ${o.chain ?? 'base-sepolia'}
      - key: ABX_PORT
        value: "${PORT}"
      - key: ABX_HOSTED
        value: "1"   # hosted image — the resolver refuses a localhost/placeholder base URL
      # With --domain we bake your domain; without one, the real onrender.com hostname so it works
      # out of the box (add a custom domain later).
      - key: ABX_PUBLIC_BASE_URL
        value: ${baseUrlFor(o)}
      - key: ABX_RPC_URLS
        sync: false   # set in the dashboard (secret); read-only RPC for this chain, NO signing key
      - key: ABX_RESOLVER_ADMIN_TOKEN
        sync: false   # set in the dashboard; authorizes remote \`abx add\`/index (NOT signing). Match ABX_REMOTE_SELF_TOKEN in your local .env.
`;
  return {
    baseUrl: baseUrlFor(o),
    files: [
      {path: 'Dockerfile', content: dockerfileFor(o)},
      {path: '.dockerignore', content: DOCKERIGNORE},
      {path: 'render.yaml', content: yaml},
    ],
    steps: [
      `commit render.yaml + the emitted Dockerfile, then in the Render dashboard: New → Blueprint → pick this repo`,
      `set ABX_RPC_URLS in the service's Environment (read-only RPC for this chain; NO signing key)`,
      `set ABX_RESOLVER_ADMIN_TOKEN to the value of ABX_REMOTE_SELF_TOKEN in your local .env (lets you remote-register contracts)`,
      o.domain ? `Settings → Custom Domains → add ${o.domain}, then add the DNS record below` : `# add a custom domain in Settings → Custom Domains`,
    ],
    dns: o.domain ? `${o.domain}  CNAME  ${o.app}.onrender.com` : undefined,
    hardening: 'HTTPS by default; health check on /health; no signing key; RPC url set as a dashboard secret.',
  };
}

/** DigitalOcean (or any) VPS — docker compose + Caddy for automatic TLS on the custom domain. */
function vps(o: ResolverOptions): ResolverArtifact {
  const domain = o.domain ?? 'meta.yourproject.xyz';
  const compose = `# Generated by \`abx deploy-resolver --provider vps\`. Builds the emitted Dockerfile in
# this dir (self-contained) and serves the read-only resolver on :${PORT}. No signing key on the host.
services:
  abx:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - abx-data:/data
    ports:
      - "127.0.0.1:${PORT}:${PORT}"   # Caddy fronts it with TLS; the app port stays loopback-only
volumes:
  abx-data:
`;
  const caddy = `# Caddy reverse-proxy with automatic TLS. Caddy fetches a cert for the domain.
${domain} {
  reverse_proxy localhost:${PORT}
}
`;
  const setup = `#!/usr/bin/env bash
# Generated by \`abx deploy-resolver --provider vps\`. Stands up the read-only ABX resolver on a
# fresh Debian/Ubuntu droplet, behind Caddy (automatic HTTPS). Run as root FROM THIS artifact dir
# (deploy/vps) after copying it to the droplet — it is self-contained (Dockerfile + compose here).
set -euo pipefail

DOMAIN="${domain}"
RPC_URL="\${ABX_RPC_URLS:?set ABX_RPC_URLS to your read-only RPC endpoint(s) for this chain}"
# Authorizes remote \`abx add\`/index (NOT on-chain signing). Must match your workstation's .env.
ADMIN_TOKEN="\${ABX_RESOLVER_ADMIN_TOKEN:?set ABX_RESOLVER_ADMIN_TOKEN (the value of ABX_REMOTE_SELF_TOKEN that abx deploy-resolver saved to your .env)}"

# 1. Docker
curl -fsSL https://get.docker.com | sh

# 2. The resolver (serves + admin index-control). NO signing key on the host — writes are signed locally.
cat > .env <<EOF
ABX_CHAIN=${o.chain ?? 'base-sepolia'}
ABX_RPC_URLS=\${RPC_URL}
ABX_PUBLIC_BASE_URL=https://\${DOMAIN}
ABX_HOSTED=1
ABX_RESOLVER_ADMIN_TOKEN=\${ADMIN_TOKEN}
EOF
docker compose up -d --build   # builds the Dockerfile in this dir

# 3. Caddy for TLS on the custom domain
apt-get update && apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
apt-get update && apt-get install -y caddy
cp Caddyfile /etc/caddy/Caddyfile && systemctl reload caddy

echo "Resolver up at https://\${DOMAIN}  (point the domain's A record at this droplet's IP first)"
`;
  return {
    baseUrl: `https://${domain}`,
    files: [
      {path: 'Dockerfile', content: dockerfileFor(o)},
      {path: '.dockerignore', content: DOCKERIGNORE},
      {path: 'docker-compose.yml', content: compose},
      {path: 'Caddyfile', content: caddy},
      {path: 'setup.sh', content: setup},
    ],
    steps: [
      `create a droplet, point ${domain}'s A record at its IP`,
      `copy THIS artifact dir (deploy/vps — it is self-contained) to the droplet`,
      `ABX_RPC_URLS=<your-rpc-url> ABX_RESOLVER_ADMIN_TOKEN=<ABX_REMOTE_SELF_TOKEN from your .env> bash setup.sh   # read-only RPC; NO signing key`,
    ],
    dns: `${domain}  A  <droplet-ip>`,
    hardening: 'Caddy auto-TLS; compose runs only `abx serve` (read-only); no signing key; app port loopback-only.',
  };
}

// ── effects runner (the render companion) ───────────────────────────────────--

export interface EffectsOptions {
  /** Fly app name for the runner (distinct from the resolver app). */
  app: string;
  /** The resolver the runner reads token state from AND publishes renders back to (ABX_RESOLVER_URL). */
  resolverUrl: string;
  chain?: string;
  /** Sweep interval (ms) — the eventual floor; a resolver ping makes renders immediate. */
  intervalMs?: number;
  environmentId?: string;
  /** The storage home renders are uploaded to (ABX_STORAGE_BACKEND) — baked as env; secrets set separately. */
  storageBackend?: string;
  /** Workspace package dirs to COPY (the runner always builds from source — no npm entrypoint yet). */
  sourcePackages: string[];
  pnpmVersion?: string;
}

/** The effects runner image — Playwright + Chromium (the resolver image stays browserless). Always a
 *  source build today (no npm `abx effects` entrypoint yet; converges to npm post-publish, like the
 *  resolver). Mirrors the committed root `Dockerfile.effects`, but self-contained for the artifact dir. */
function effectsDockerfile(o: EffectsOptions): string {
  const copyManifests = o.sourcePackages.map((p) => `COPY ${p}/package.json ${p}/`).join('\n');
  return `# Generated by \`abx deploy-effects\`. The effects runner — the ONLY image carrying a browser
# (Playwright + Chromium), so the resolver image stays small. It renders each code token's live view
# and PUBLISHES the result to the resolver (a durable locator, or bytes) — or writes a shared backend.
FROM mcr.microsoft.com/playwright:v1.61.1-noble
RUN corepack enable && corepack prepare pnpm@${o.pnpmVersion ?? '10.28.0'} --activate
WORKDIR /app
# Deps first for layer caching — every workspace package.json must be copied (a missing one fails at
# runtime, not install time).
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
${copyManifests}
# The lockfile pins playwright to the EXACT version whose browsers this base image ships (the FROM
# tag above) — bump both together, never one.
RUN pnpm install --frozen-lockfile
COPY packages packages
ENV ABX_EFFECTS_PORT=8788
EXPOSE 8788
ENTRYPOINT ["pnpm", "abx-effects"]
`;
}

/** Fly artifact for the effects runner — a companion to `deploy-resolver`. Emits its own self-contained
 *  Dockerfile.effects + fly.toml (with the browser image + a memory bump Chromium needs). */
export function effectsArtifact(o: EffectsOptions): ResolverArtifact {
  const port = 8788;
  const toml = `# Generated by \`abx deploy-effects --provider fly\`. The effects runner, beside your resolver.
app = "${o.app}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.effects"

[env]
  ABX_CHAIN = "${o.chain ?? 'base-sepolia'}"
  # The resolver this runner serves: it reads token state from here and publishes each render back.
  ABX_RESOLVER_URL = "${o.resolverUrl}"
  ABX_EFFECTS_PORT = "${port}"
  # SAFETY FLOOR only — the resolver's chain watcher POSTs /notify the moment settled state
  # changes; this sweep just catches a missed ping / cold start / a newly-registered project.
  ABX_EFFECTS_INTERVAL_MS = "${o.intervalMs ?? 300_000}"
  ABX_ENVIRONMENT_ID = "${o.environmentId ?? 'web:any'}"${o.storageBackend ? `\n  ABX_STORAGE_BACKEND = "${o.storageBackend}"` : ''}

[http_service]
  internal_port = ${port}
  force_https = true
  auto_stop_machines = false   # a worker: keep it up so the periodic sweep (the eventual floor) runs
  auto_start_machines = true
  min_machines_running = 1

# Chromium wants headroom — the default shared 256MB OOMs mid-render.
[[vm]]
  memory = "1gb"
`;
  return {
    baseUrl: o.resolverUrl,
    files: [
      {path: 'Dockerfile.effects', content: effectsDockerfile(o)},
      {path: '.dockerignore', content: DOCKERIGNORE},
      {path: 'fly.toml', content: toml},
    ],
    steps: [
      `fly version && fly auth whoami   # confirm fly is installed + you're logged in ('flyctl' and 'fly' are the same binary)`,
      `fly launch --no-deploy --copy-config --name ${o.app}   # uses Dockerfile.effects + fly.toml in THIS dir`,
      loadEnv,
      `fly secrets set ABX_RPC_URLS="$ABX_RPC_URLS"   # augment hooks / data-backed params need reads`,
      // LHS is the resolver's OWN var name (server-side); RHS is your local ABX_REMOTE_SELF_TOKEN.
      `fly secrets set ABX_RESOLVER_ADMIN_TOKEN="$ABX_REMOTE_SELF_TOKEN"   # the SAME token as the resolver — publishing is admin-gated`,
      `fly secrets set ABX_EFFECTS_TOKEN="$ABX_EFFECTS_TOKEN"   # gates this PUBLIC runner's /run + /notify (an open force-render endpoint burns Chromium/storage)`,
      `# set your storage-home secrets so renders land where the resolver can read them, e.g.:`,
      `#   fly secrets set PINATA_JWT="$PINATA_JWT"                              (ipfs)`,
      // ARWEAVE_JWK (the JWK inline), NOT ABX_ARWEAVE_KEY — no such var is read anywhere, so the
      // old line was a silent no-op for anyone who pasted it: the runner would come up with no
      // Arweave identity and fail at its first upload, pointing at a variable that was "set".
      // The hosted runner cannot use the CLI's managed key file (that lives on the operator's
      // machine), so the inline form is the one that applies here.
      `#   fly secrets set ARWEAVE_JWK="$(cat .abx-self-host/arweave-key.json)"   (arweave — the JWK itself; ABX_ARWEAVE_KEY_FILE is a local path and won't help a remote host)`,
      `#   fly secrets set ABX_S3_ACCESS_KEY_ID="$ABX_S3_ACCESS_KEY_ID" ABX_S3_SECRET_ACCESS_KEY="$ABX_S3_SECRET_ACCESS_KEY"   (s3/cloud)`,
      `fly deploy`,
      `# WIRE THE WATCHER — on the RESOLVER app, point its chain watcher at this runner (this is what`,
      `# makes every external mint / param change auto-render; the sweep is only the safety floor):`,
      `fly secrets set --app <your-resolver-app> ABX_EFFECTS_URL="https://${o.app}.fly.dev" ABX_EFFECTS_TOKEN="$ABX_EFFECTS_TOKEN"`,
    ],
    hardening: 'renders in a sandboxed browser; /run + /notify are bearer-gated (ABX_EFFECTS_TOKEN); publishes via the admin token (never a signing key); talks OUT to the resolver.',
  };
}

const BUILDERS: Record<ResolverProvider, (o: ResolverOptions) => ResolverArtifact> = {fly, render, vps};

export function resolverArtifact(opts: ResolverOptions): ResolverArtifact {
  const build = BUILDERS[opts.provider];
  if (!build) throw new Error(`unknown provider '${opts.provider}' — one of: ${Object.keys(BUILDERS).join(', ')}`);
  return build(opts);
}
